# Generated by Django 4.1.4 on 2022-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosets',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='photosets',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
